"""Updated at activity log

Revision ID: a58d9fcb63d1
Revises: dc39dca80d74
Create Date: 2024-11-29 22:11:30.375804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58d9fcb63d1'
down_revision: Union[str, None] = 'dc39dca80d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'updated_at')
    # ### end Alembic commands ###
