"""ne vstat

Revision ID: b550b9d9739c
Revises: 3b03ea14d19f
Create Date: 2024-11-30 03:20:29.063115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b550b9d9739c'
down_revision: Union[str, None] = '3b03ea14d19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_instructor_id', table_name='courses')
    op.drop_constraint('courses_instructor_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'instructor_id')
    op.drop_column('courses', 'duration_weeks')
    op.add_column('schedules', sa.Column('code', sa.String(length=10), nullable=False))
    op.add_column('schedules', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('schedules', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('schedules', sa.Column('end_time', sa.Time(), nullable=False))
    op.drop_index('ix_schedules_lesson_id', table_name='schedules')
    op.drop_index('ix_schedules_student_id', table_name='schedules')
    op.create_index(op.f('ix_schedules_code'), 'schedules', ['code'], unique=False)
    op.drop_constraint('schedules_lesson_id_fkey', 'schedules', type_='foreignkey')
    op.drop_constraint('schedules_student_id_fkey', 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'lesson_id')
    op.drop_column('schedules', 'created_at')
    op.drop_column('schedules', 'student_id')
    op.drop_column('schedules', 'scheduled_date')
    op.drop_column('schedules', 'completion_metadata')
    op.drop_column('schedules', 'is_completed')
    op.drop_column('schedules', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('completion_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('scheduled_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('schedules', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('schedules_student_id_fkey', 'schedules', 'users', ['student_id'], ['id'])
    op.create_foreign_key('schedules_lesson_id_fkey', 'schedules', 'lessons', ['lesson_id'], ['id'])
    op.drop_index(op.f('ix_schedules_code'), table_name='schedules')
    op.create_index('ix_schedules_student_id', 'schedules', ['student_id'], unique=False)
    op.create_index('ix_schedules_lesson_id', 'schedules', ['lesson_id'], unique=False)
    op.drop_column('schedules', 'end_time')
    op.drop_column('schedules', 'start_time')
    op.drop_column('schedules', 'day_of_week')
    op.drop_column('schedules', 'code')
    op.add_column('courses', sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_instructor_id_fkey', 'courses', 'users', ['instructor_id'], ['id'])
    op.create_index('ix_courses_instructor_id', 'courses', ['instructor_id'], unique=False)
    # ### end Alembic commands ###
